/* 
    UPDATES.JS - Dynamic Configuration
    Generated by Admin Panel
    Save this file to "js/updates.js" to publish changes.
*/

// 1. Hidden Content Configuration
App.setHiddenProjects([]);
App.setHiddenBlogs(["finecraft","nisarga","ira"]);

// 2. Custom Reviews

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Krishnakumar",
    role: "Private Residence owner",
    text: `Was looking to overhaul the interior areas in my home. Nexhaus helped me in making it a reality.` // Escape backticks
});

App.addReview({
    client: "Maheshwari",
    role: "Founder Maya by Maheshwari",
    text: `Nexhaus helped in PMC for one of our stores in Trivandrum. It was an easy turnaround for the store with them.` // Escape backticks
});

App.addReview({
    client: "Riyas A T",
    role: "Private Residence Owner",
    text: `Nexhaus provided the much needed confidence on building residence.` // Escape backticks
});
